### ISSUE TITLE
Smart TV LG WebOS SSIPTV incompatible

### ISSUE THREAD

**Issue by manueldev** [back-to/liveproxy#3]
I am trying to play from a LG Smart TV using the SS IPTV application with no results. This is the log generated by liveproxy when the connection occurs:

```
[liveproxy-main][info] For LiveProxy support visit https://github.com/back-to/liveproxy
[liveproxy-main][debug] OS:            macOS 10.14
[liveproxy-main][debug] Python:        2.7.15
[liveproxy-main][debug] LiveProxy:     0.0.4.dev0
[liveproxy-main][debug] Streamlink:    0.14.2+102.g0599dc66
[liveproxy-main][debug] Requests(2.19.1), Websocket(0.53.0)
[liveproxy-main][info] Starting server: 0.0.0.0 on port 53422
[liveproxy-server][info] User-Agent: Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36 WebAppManager
[liveproxy-server][info] Client: ('192.168.0.16', 40634)
[liveproxy-server][info] Address: 192.168.0.16
[liveproxy-server][info] Plugin path /Users/user/.config/streamlink/plugins does not exist or is not a directory!
[liveproxy-server][info] Found matching plugin hls for URL https://server/playlist.m3u8
[plugin.hls][debug] URL=https://server/playlist.m3u8; params={}
[utils.l10n][debug] Language code: en_US
[liveproxy-server][info] User-Agent: Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36 WebAppManager
[liveproxy-server][info] Client: ('192.168.0.16', 40636)
[liveproxy-server][info] Address: 192.168.0.16
[liveproxy-server][info] Plugin path /Users/user/.config/streamlink/plugins does not exist or is not a directory!
[liveproxy-server][info] Found matching plugin hls for URL https://server/playlist.m3u8
[plugin.hls][debug] URL=https://server/playlist.m3u8; params={}
[utils.l10n][debug] Language code: en_US
[liveproxy-server][info] Available streams: 478k (worst), 1091k, 1397k, 2010k, 2726k, 3747k (best)
[liveproxy-server][info] Opening stream: 3747k (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] First Sequence: 153772477; Last Sequence: 153772488
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 153772479; End Sequence: None
[stream.hls][debug] Adding segment 153772479 to queue
[liveproxy-server][debug] 192.168.0.16 - "GET /play/?url=https%3A%2F%2Fserver%2Fplaylist.m3u8&hls-segment-attempts=20&hls-segment-timeout=20&hls-live-edge=10&hls-segment-thread=3&loglevel=debug&?.ts HTTP/1.1" 200 -
[stream.hls][debug] Adding segment 153772480 to queue
[stream.hls][debug] Adding segment 153772481 to queue
[liveproxy-server][debug] Pre-buffering 4096 bytes
[stream.hls][debug] Adding segment 153772482 to queue
[stream.hls][debug] Adding segment 153772483 to queue
[stream.hls][debug] Adding segment 153772484 to queue
[stream.hls][debug] Adding segment 153772485 to queue
[stream.hls][debug] Adding segment 153772486 to queue
[stream.hls][debug] Adding segment 153772487 to queue
[stream.hls][debug] Adding segment 153772488 to queue
[liveproxy-server][info] Available streams: 478k (worst), 1091k, 1397k, 2010k, 2726k, 3747k (best)
[liveproxy-server][info] Opening stream: 3747k (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] First Sequence: 153772477; Last Sequence: 153772488
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 153772479; End Sequence: None
[stream.hls][debug] Adding segment 153772479 to queue
[stream.hls][debug] Adding segment 153772480 to queue
[liveproxy-server][debug] 192.168.0.16 - "GET /play/?url=https%3A%2F%2Fserver%2Fplaylist.m3u8&hls-segment-attempts=20&hls-segment-timeout=20&hls-live-edge=10&hls-segment-thread=3&loglevel=debug&?.ts HTTP/1.1" 200 -
[stream.hls][debug] Adding segment 153772481 to queue
[stream.hls][debug] Adding segment 153772482 to queue
[stream.hls][debug] Adding segment 153772483 to queue
[liveproxy-server][debug] Pre-buffering 4096 bytes
[stream.hls][debug] Adding segment 153772484 to queue
[stream.hls][debug] Adding segment 153772485 to queue
[stream.hls][debug] Adding segment 153772486 to queue
[stream.hls][debug] Adding segment 153772487 to queue
[stream.hls][debug] Adding segment 153772488 to queue
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 153772479 complete
[stream.hls][debug] Download of segment 153772480 complete
[liveproxy-server][info] Detected remote disconnect
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[liveproxy-server][info] Stream ended
----------------------------------------
Exception happened during processing of request from ('192.168.0.16', 40634)
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Download of segment 153772481 complete
[stream.hls][debug] Download of segment 153772479 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Download of segment 153772480 complete
[stream.hls][debug] Download of segment 153772481 complete
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 153772489 to queue
[stream.hls][debug] Download of segment 153772482 complete
[stream.hls][debug] Download of segment 153772483 complete
[stream.hls][debug] Download of segment 153772484 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Segments in this playlist are encrypted
[stream.hls][debug] Adding segment 153772490 to queue
[stream.hls][debug] Download of segment 153772485 complete
[stream.hls][debug] Download of segment 153772486 complete
[stream.hls][debug] Download of segment 153772487 complete
[liveproxy-server][info] Detected remote disconnect
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[liveproxy-server][info] Stream ended
----------------------------------------
Exception happened during processing of request from ('192.168.0.16', 40636)
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
```

I tried playing a link "http://topchantv.net:3456/live/911TV_TEST/911tv.info/6.ts" using SS IPTV with no problems (this is the http header that shows ffmpeg, maybe it gives us a clue):

```
[http @ 0x7fbc39506340] header='HTTP/1.1 200 OK'
[http @ 0x7fbc39506340] http_code=200
[http @ 0x7fbc39506340] header='Server: nginx'
[http @ 0x7fbc39506340] header='Date: Sun, 23 Sep 2018 12:29:18 GMT'
[http @ 0x7fbc39506340] header='Content-Type: video/mp2t'
[http @ 0x7fbc39506340] header='Connection: close'
[http @ 0x7fbc39506340] header='Access-Control-Allow-Origin: *'
```

**Comment by back-to** [comment]
`SS IPTV` crashes on normal `mp4` URLs for me,
can't help you with this issue.
