### ISSUE TITLE
base64 TypeError: Incorrect padding

### ISSUE THREAD

**Issue by jimsmt** [back-to/liveproxy#8]
liveproxy version 0.3.0

base64 encoded command

`c3RyZWFtbGluayAtLWh0dHBzLXByb3h5ICJzb2NrczVoOi8vMTkyLjE2OC4yLjE6MTA4MCIgaHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj15azJDVWpieXlRWSBiZXN0`

will cause error

```
Exception happened during processing of request from ('192.168.2.185', 8770)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/dist-packages/liveproxy/server.py", line 589, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/local/lib/python2.7/dist-packages/liveproxy/server.py", line 574, in do_GET
    arglist = shlex.split(base64.b64decode(base64_path[2]).decode('UTF-8'))
  File "/usr/lib/python2.7/base64.py", line 78, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.168.2.185', 8771)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/dist-packages/liveproxy/server.py", line 589, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/local/lib/python2.7/dist-packages/liveproxy/server.py", line 574, in do_GET
    arglist = shlex.split(base64.b64decode(base64_path[2]).decode('UTF-8'))
  File "/usr/lib/python2.7/base64.py", line 78, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding
----------------------------------------
```

**Comment by L2501** [comment]
This is a breaking change, maybe a new version release?
